# Same as environment.yml without NILMTK and NILM metadata packages
name: nilmtk-env
channels:
    - conda-forge
    - nilmtk
dependencies:
- python>=3.9
- numpy
- pytables
- pandas
- matplotlib-base
- networkx
- scipy
- scikit-learn
- jupyterlab
- nose
- coverage
- pip
- coveralls
- hmmlearn
- nilm_metadata
