name: nilmtk-env
channels:
    - conda-forge
    - nilmtk
dependencies:
- python>=3.9
- numpy
- pytables
- pandas>=1.5
- matplotlib-base
- networkx>=3.0
- scipy
- scikit-learn
- jupyterlab
- nose
- nilm_metadata
- nilmtk
- hmmlearn
