name: nilmtk-env
channels:
    - conda-forge
    - nilmtk
dependencies:
- python>=3.6
- numpy
- pytables
- pandas
- matplotlib-base
- networkx==2.1
- scipy
- scikit-learn
- jupyterlab
- nose
- nilm_metadata
- nilmtk
- hmmlearn
